export const REMOVE_WIDGET_TIMEOUT = 600;
export const GENERATE_WIDGET_TIMEOUT = 1000;
export const GENERATE_WIDGET_BOARD_TIMEOUT = 1000;
export const MIN_ROW = 6;
export default {
  REMOVE_WIDGET_TIMEOUT,
  GENERATE_WIDGET_TIMEOUT,
  GENERATE_WIDGET_BOARD_TIMEOUT,
  MIN_ROW
};
