export const GLOBAL_REGION_ID = 22;
export const ASIA_REGION_ID = 26;
export const AUSTRALAISIA_REGION_ID = 10;
export const NORTH_AMERICA_REGION_ID = 1;
export const NATIONS_STRING_ARRAY = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'French Guiana',
  'Gabon',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  "Korea, Democratic People's Republic",
  'Korea, Republic of',
  'Kuwait',
  'Kyrgyzstan',
  'Lao PDR',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of the Congo',
  'Réunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Samoa',
  'San Marino',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'UK',
  'Ukraine',
  'United Arab Emirates',
  'Unknown',
  'Uruguay',
  'US',
  'US Virgin Islands',
  'Uzbekistan',
  'Venezuela (Bolivarian Republic of)',
  'Vietnam',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

export const NATION_OBJECT_ARRAY = [
  { Country_id: 1, Country_name: 'Afghanistan' },
  { Country_id: 2, Country_name: 'Albania' },
  { Country_id: 3, Country_name: 'Algeria' },
  { Country_id: 4, Country_name: 'Andorra' },
  { Country_id: 5, Country_name: 'Angola' },
  { Country_id: 6, Country_name: 'Anguilla' },
  { Country_id: 7, Country_name: 'Antigua and Barbuda' },
  { Country_id: 8, Country_name: 'Argentina' },
  { Country_id: 9, Country_name: 'Armenia' },
  { Country_id: 10, Country_name: 'Aruba' },
  { Country_id: 11, Country_name: 'Australia' },
  { Country_id: 12, Country_name: 'Austria' },
  { Country_id: 13, Country_name: 'Azerbaijan' },
  { Country_id: 14, Country_name: 'Bahamas' },
  { Country_id: 15, Country_name: 'Bahrain' },
  { Country_id: 16, Country_name: 'Bangladesh' },
  { Country_id: 17, Country_name: 'Barbados' },
  { Country_id: 18, Country_name: 'Belarus' },
  { Country_id: 19, Country_name: 'Belgium' },
  { Country_id: 20, Country_name: 'Belize' },
  { Country_id: 21, Country_name: 'Benin' },
  { Country_id: 22, Country_name: 'Bermuda' },
  { Country_id: 23, Country_name: 'Bhutan' },
  { Country_id: 24, Country_name: 'Bolivia' },
  { Country_id: 25, Country_name: 'Bosnia and Herzegovina' },
  { Country_id: 26, Country_name: 'Botswana' },
  { Country_id: 27, Country_name: 'Brazil' },
  { Country_id: 28, Country_name: 'British Virgin Islands' },
  { Country_id: 29, Country_name: 'Brunei Darussalam' },
  { Country_id: 30, Country_name: 'Bulgaria' },
  { Country_id: 31, Country_name: 'Burkina Faso' },
  { Country_id: 32, Country_name: 'Burundi' },
  { Country_id: 33, Country_name: 'Cambodia' },
  { Country_id: 34, Country_name: 'Cameroon' },
  { Country_id: 35, Country_name: 'Canada' },
  { Country_id: 36, Country_name: 'Cape Verde' },
  { Country_id: 37, Country_name: 'Cayman Islands' },
  { Country_id: 38, Country_name: 'Central African Republic' },
  { Country_id: 39, Country_name: 'Chad' },
  { Country_id: 40, Country_name: 'Chile' },
  { Country_id: 41, Country_name: 'China' },
  { Country_id: 43, Country_name: 'Colombia' },
  { Country_id: 44, Country_name: 'Comoros' },
  { Country_id: 45, Country_name: 'Costa Rica' },
  { Country_id: 46, Country_name: 'Croatia' },
  { Country_id: 47, Country_name: 'Cuba' },
  { Country_id: 48, Country_name: 'Cyprus' },
  { Country_id: 49, Country_name: 'Czech Republic' },
  { Country_id: 198, Country_name: 'Democratic Republic of Congo' },
  { Country_id: 50, Country_name: 'Denmark' },
  { Country_id: 51, Country_name: 'Djibouti' },
  { Country_id: 52, Country_name: 'Dominica' },
  { Country_id: 53, Country_name: 'Dominican Republic' },
  { Country_id: 54, Country_name: 'Ecuador' },
  { Country_id: 55, Country_name: 'Egypt' },
  { Country_id: 56, Country_name: 'El Salvador' },
  { Country_id: 57, Country_name: 'Equatorial Guinea' },
  { Country_id: 58, Country_name: 'Eritrea' },
  { Country_id: 59, Country_name: 'Estonia' },
  { Country_id: 60, Country_name: 'Ethiopia' },
  { Country_id: 61, Country_name: 'Finland' },
  { Country_id: 62, Country_name: 'France' },
  { Country_id: 63, Country_name: 'French Guiana' },
  { Country_id: 64, Country_name: 'Gabon' },
  { Country_id: 65, Country_name: 'Georgia' },
  { Country_id: 66, Country_name: 'Germany' },
  { Country_id: 67, Country_name: 'Ghana' },
  { Country_id: 68, Country_name: 'Gibraltar' },
  { Country_id: 69, Country_name: 'Greece' },
  { Country_id: 70, Country_name: 'Greenland' },
  { Country_id: 71, Country_name: 'Grenada' },
  { Country_id: 72, Country_name: 'Guadeloupe' },
  { Country_id: 73, Country_name: 'Guatemala' },
  { Country_id: 74, Country_name: 'Guernsey' },
  { Country_id: 75, Country_name: 'Guinea' },
  { Country_id: 76, Country_name: 'Guinea-Bissau' },
  { Country_id: 77, Country_name: 'Guyana' },
  { Country_id: 78, Country_name: 'Haiti' },
  { Country_id: 79, Country_name: 'Honduras' },
  { Country_id: 42, Country_name: 'Hong Kong' },
  { Country_id: 80, Country_name: 'Hungary' },
  { Country_id: 81, Country_name: 'Iceland' },
  { Country_id: 82, Country_name: 'India' },
  { Country_id: 83, Country_name: 'Indonesia' },
  { Country_id: 84, Country_name: 'Iran' },
  { Country_id: 85, Country_name: 'Iraq' },
  { Country_id: 86, Country_name: 'Ireland' },
  { Country_id: 87, Country_name: 'Isle of Man' },
  { Country_id: 88, Country_name: 'Israel' },
  { Country_id: 89, Country_name: 'Italy' },
  { Country_id: 197, Country_name: 'Ivory Coast' },
  { Country_id: 90, Country_name: 'Jamaica' },
  { Country_id: 91, Country_name: 'Japan' },
  { Country_id: 92, Country_name: 'Jersey' },
  { Country_id: 93, Country_name: 'Jordan' },
  { Country_id: 94, Country_name: 'Kazakhstan' },
  { Country_id: 95, Country_name: 'Kenya' },
  { Country_id: 96, Country_name: "Korea, Democratic People's Republic" },
  { Country_id: 97, Country_name: 'Korea, Republic of' },
  { Country_id: 98, Country_name: 'Kuwait' },
  { Country_id: 99, Country_name: 'Kyrgyzstan' },
  { Country_id: 100, Country_name: 'Lao PDR' },
  { Country_id: 101, Country_name: 'Latvia' },
  { Country_id: 102, Country_name: 'Lebanon' },
  { Country_id: 103, Country_name: 'Lesotho' },
  { Country_id: 104, Country_name: 'Liberia' },
  { Country_id: 193, Country_name: 'Libya' },
  { Country_id: 105, Country_name: 'Liechtenstein' },
  { Country_id: 106, Country_name: 'Lithuania' },
  { Country_id: 107, Country_name: 'Luxembourg' },
  { Country_id: 192, Country_name: 'Macedonia' },
  { Country_id: 108, Country_name: 'Madagascar' },
  { Country_id: 109, Country_name: 'Malawi' },
  { Country_id: 195, Country_name: 'Malawi' },
  { Country_id: 110, Country_name: 'Malaysia' },
  { Country_id: 111, Country_name: 'Maldives' },
  { Country_id: 112, Country_name: 'Mali' },
  { Country_id: 113, Country_name: 'Malta' },
  { Country_id: 194, Country_name: 'Marshall Islands' },
  { Country_id: 114, Country_name: 'Martinique' },
  { Country_id: 115, Country_name: 'Mauritania' },
  { Country_id: 116, Country_name: 'Mauritius' },
  { Country_id: 117, Country_name: 'Mexico' },
  { Country_id: 118, Country_name: 'Moldova' },
  { Country_id: 119, Country_name: 'Monaco' },
  { Country_id: 120, Country_name: 'Mongolia' },
  { Country_id: 121, Country_name: 'Montenegro' },
  { Country_id: 122, Country_name: 'Montserrat' },
  { Country_id: 123, Country_name: 'Morocco' },
  { Country_id: 124, Country_name: 'Mozambique' },
  { Country_id: 190, Country_name: 'Myanmar' },
  { Country_id: 125, Country_name: 'Namibia' },
  { Country_id: 126, Country_name: 'Nepal' },
  { Country_id: 127, Country_name: 'Netherlands' },
  { Country_id: 128, Country_name: 'Netherlands Antilles' },
  { Country_id: 200, Country_name: 'New Caledonia' },
  { Country_id: 129, Country_name: 'New Zealand' },
  { Country_id: 130, Country_name: 'Nicaragua' },
  { Country_id: 131, Country_name: 'Niger' },
  { Country_id: 132, Country_name: 'Nigeria' },
  { Country_id: 133, Country_name: 'Norway' },
  { Country_id: 134, Country_name: 'Oman' },
  { Country_id: 135, Country_name: 'Pakistan' },
  { Country_id: 136, Country_name: 'Panama' },
  { Country_id: 196, Country_name: 'Papua New Guinea' },
  { Country_id: 137, Country_name: 'Paraguay' },
  { Country_id: 138, Country_name: 'Peru' },
  { Country_id: 139, Country_name: 'Philippines' },
  { Country_id: 140, Country_name: 'Poland' },
  { Country_id: 141, Country_name: 'Portugal' },
  { Country_id: 142, Country_name: 'Puerto Rico' },
  { Country_id: 143, Country_name: 'Qatar' },
  { Country_id: 202, Country_name: 'Republic of the Congo' },
  { Country_id: 144, Country_name: 'Réunion' },
  { Country_id: 145, Country_name: 'Romania' },
  { Country_id: 146, Country_name: 'Russian Federation' },
  { Country_id: 147, Country_name: 'Rwanda' },
  { Country_id: 148, Country_name: 'Saint Kitts and Nevis' },
  { Country_id: 149, Country_name: 'Saint Lucia' },
  { Country_id: 199, Country_name: 'Samoa' },
  { Country_id: 150, Country_name: 'San Marino' },
  { Country_id: 151, Country_name: 'Saudi Arabia' },
  { Country_id: 152, Country_name: 'Senegal' },
  { Country_id: 153, Country_name: 'Serbia' },
  { Country_id: 154, Country_name: 'Seychelles' },
  { Country_id: 155, Country_name: 'Sierra Leone' },
  { Country_id: 156, Country_name: 'Singapore' },
  { Country_id: 157, Country_name: 'Slovakia' },
  { Country_id: 158, Country_name: 'Slovenia' },
  { Country_id: 159, Country_name: 'Somalia' },
  { Country_id: 160, Country_name: 'South Africa' },
  { Country_id: 203, Country_name: 'South Sudan' },
  { Country_id: 161, Country_name: 'Spain' },
  { Country_id: 162, Country_name: 'Sri Lanka' },
  { Country_id: 163, Country_name: 'Sudan' },
  { Country_id: 164, Country_name: 'Suriname' },
  { Country_id: 165, Country_name: 'Swaziland' },
  { Country_id: 166, Country_name: 'Sweden' },
  { Country_id: 167, Country_name: 'Switzerland' },
  { Country_id: 201, Country_name: 'Syria' },
  { Country_id: 168, Country_name: 'Taiwan' },
  { Country_id: 169, Country_name: 'Tajikistan' },
  { Country_id: 170, Country_name: 'Tanzania' },
  { Country_id: 171, Country_name: 'Thailand' },
  { Country_id: 172, Country_name: 'Togo' },
  { Country_id: 173, Country_name: 'Trinidad and Tobago' },
  { Country_id: 174, Country_name: 'Tunisia' },
  { Country_id: 175, Country_name: 'Turkey' },
  { Country_id: 176, Country_name: 'Turkmenistan' },
  { Country_id: 177, Country_name: 'Uganda' },
  { Country_id: 180, Country_name: 'UK' },
  { Country_id: 178, Country_name: 'Ukraine' },
  { Country_id: 179, Country_name: 'United Arab Emirates' },
  { Country_id: 191, Country_name: 'Unknown' },
  { Country_id: 182, Country_name: 'Uruguay' },
  { Country_id: 181, Country_name: 'US' },
  { Country_id: 186, Country_name: 'US Virgin Islands' },
  { Country_id: 183, Country_name: 'Uzbekistan' },
  { Country_id: 184, Country_name: 'Venezuela (Bolivarian Republic of)' },
  { Country_id: 185, Country_name: 'Vietnam' },
  { Country_id: 204, Country_name: 'Western Sahara' },
  { Country_id: 187, Country_name: 'Yemen' },
  { Country_id: 188, Country_name: 'Zambia' },
  { Country_id: 189, Country_name: 'Zimbabwe' }
];

export default {
  NATIONS_STRING_ARRAY,
  NATION_OBJECT_ARRAY,
  GLOBAL_REGION_ID,
  ASIA_REGION_ID,
  AUSTRALAISIA_REGION_ID,
  NORTH_AMERICA_REGION_ID
};
