export const ADVANCED_VOTING_DATA_SEARCH_TOOL = 1;
export const RESOLUTION_TRACKER_TOOL = 2;
export const NO_ACTION_LETTER_TOOL = 3;
export const INVESTOR_COMPARATOR_TOOL = 4;
export const DISSIDENT_VOTING_SUMMARY_TOOL = 5;
export const COMPANYGOVERNANCEDATAANDANALYTICS_TOOL = 6;
export const DIRECTORDATAANDANALYTICS_TOOL = 7;
export const COMPANYPEERGROUP_COMPARISON_MATRIX_TOOL = 8;

export default {
  ADVANCED_VOTING_DATA_SEARCH_TOOL,
  RESOLUTION_TRACKER_TOOL,
  NO_ACTION_LETTER_TOOL,
  INVESTOR_COMPARATOR_TOOL,
  DISSIDENT_VOTING_SUMMARY_TOOL,
  COMPANYGOVERNANCEDATAANDANALYTICS_TOOL,
  DIRECTORDATAANDANALYTICS_TOOL,
  COMPANYPEERGROUP_COMPARISON_MATRIX_TOOL,
};
