export const SHORT_ACTIVISM_DEFAULT_DDL_COUNTRY_LABEL = 'All Countries';
export const SHORT_ACTIVISM_DEFAULT_DDL_COUNTRY_VALUE = -1;

export default {
  SHORT_ACTIVISM_DEFAULT_DDL_COUNTRY_VALUE,
  SHORT_ACTIVISM_DEFAULT_DDL_COUNTRY_LABEL
};
