export const ACTIVIST_CAMPAIGN_WEBSITES = 22;
export const MOST_VULNERABLE_COMPANIES = 58;
export const INVESTOR_POLICY_CHANGES = 37;
export const PROXY_ADVISOR_RECOMMENDATION = 38;
export const RIGHTS_AGREEMENT_ADOPTION = 59;
export const CHARTER_AMENDMENT = 24;
export const ACTIVIST_DIRECTOR_NOMINATION = 25;
export const MEETING = 26;
export const TOP_ACTIVIST_SHORT_SELLERS = 56;
export const KEY_PROPOSALS = 46;
export const ACTIVIST_SHORT_CAMPAIGN = 50;
export const ACTIVIST_SHORT_CAMPAIGN_CHART = 52;
export const MOST_SHORTED_STOCKS = 53;
export const RECENTLY_NOTIFIED_SHORT_POSITIONS = 54;
export const TIMELINES_SHORTS = 55;
export const RIGHTS_AGREEMENT_ADOPTION_CHART = 61;
export const CONTACT_CHANGES = 44;
export const AUDITOR_APPOINTMENT = 63;
export const AUDITOR_RESIGNATION = 64;
export const TIMELINES_ACTIVISM = 18;
export const ACTIVIST_CAMPAIGNS_CHART = 19;
export const ACTIVIST_CAMPAIGNS_WORLD_MAP = 20;
export const NEW_ACTIVIST_INVESTORS = 21;
export const ACTIVIST_CAMPAIGNS = 1;
export const BOARD_SEATS_WON = 2;
export const DEMAND_OUTCOMES = 3;
export const EXECUTIVE_DIRECTOR_UPDATES = 23;
export const MEETING_RESULTS = 29;
export const ANNUAL_REPORT = 30;
export const PROXY_STATEMENT = 31;
export const SETTLEMENT_FOR_BOARD_SEATS = 7;
export const NOTIFIED_STAKES = 8;
export const ACTIVIST_WHITE_PAPER = 12;
export const DEADLINE_DATE_INCLUSION_IN_PROXY_STATEMENT = 34;
export const DEADLINE_DATE_NOT_FOR_INCLUSION_IN_PROXY_STATEMENT = 36;
export const KEY_PROPOSALS_UPCOMING = 49;
export const PROXY_CONTEST_MEETING = 5;
export const STANDSTILL_EXPIRY = 6;
export const RIGHTS_AGREEMENT_EXPIRY = 62;
export const EXECUTIVE_DIRECTOR_UPDATES_UPCOMING = 68;
export const NEWS = 69;
export const VOTING_MEETINGS = 70;
export const VOTING_MEETING_RESULTS = 71;
export const VOTING_PROXY_STATEMENT = 72;

//Compensation
export const LATEST_COMPENSATION_RELEASES = 77;
export const LATEST_CEO_PAY_RATIO = 78;
export const TOP20_HIGHEST_PAID_EXECUTIVES = 79;
export const AVERAGE_GLOBAL_CEO_PAY_BREAKDOWN_REALIZED = 80;
//

export default {
  ACTIVIST_CAMPAIGN_WEBSITES,
  MOST_VULNERABLE_COMPANIES,
  INVESTOR_POLICY_CHANGES,
  PROXY_ADVISOR_RECOMMENDATION,
  RIGHTS_AGREEMENT_ADOPTION,
  CHARTER_AMENDMENT,
  ACTIVIST_DIRECTOR_NOMINATION,
  MEETING,
  TOP_ACTIVIST_SHORT_SELLERS,
  KEY_PROPOSALS,
  ACTIVIST_SHORT_CAMPAIGN,
  ACTIVIST_SHORT_CAMPAIGN_CHART,
  MOST_SHORTED_STOCKS,
  RECENTLY_NOTIFIED_SHORT_POSITIONS,
  TIMELINES_SHORTS,
  RIGHTS_AGREEMENT_ADOPTION_CHART,
  CONTACT_CHANGES,
  AUDITOR_APPOINTMENT,
  AUDITOR_RESIGNATION,
  TIMELINES_ACTIVISM,
  ACTIVIST_CAMPAIGNS_CHART,
  ACTIVIST_CAMPAIGNS_WORLD_MAP,
  NEW_ACTIVIST_INVESTORS,
  ACTIVIST_CAMPAIGNS,
  BOARD_SEATS_WON,
  DEMAND_OUTCOMES,
  EXECUTIVE_DIRECTOR_UPDATES,
  MEETING_RESULTS,
  ANNUAL_REPORT,
  PROXY_STATEMENT,
  SETTLEMENT_FOR_BOARD_SEATS,
  NOTIFIED_STAKES,
  ACTIVIST_WHITE_PAPER,
  NEWS,
  DEADLINE_DATE_INCLUSION_IN_PROXY_STATEMENT,
  DEADLINE_DATE_NOT_FOR_INCLUSION_IN_PROXY_STATEMENT,
  KEY_PROPOSALS_UPCOMING,
  PROXY_CONTEST_MEETING,
  STANDSTILL_EXPIRY,
  RIGHTS_AGREEMENT_EXPIRY,
  EXECUTIVE_DIRECTOR_UPDATES_UPCOMING,
  VOTING_MEETINGS,
  VOTING_MEETING_RESULTS,
  VOTING_PROXY_STATEMENT,
  LATEST_COMPENSATION_RELEASES,
  LATEST_CEO_PAY_RATIO,
  TOP20_HIGHEST_PAID_EXECUTIVES,
  AVERAGE_GLOBAL_CEO_PAY_BREAKDOWN_REALIZED
};
